spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:8080
    username:
    password:
  jpa:
    hibernate.ddl-auto: create
    generate-ddl: true
    show-sql: true